/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IMetaCompany } from "./IMetaCompany";
export type { IMetaFranchise } from "./IMetaFranchise";
export type { IMetaShare } from "./IMetaShare";
