/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  ICronusTimeOracle,
  ICronusTimeOracleInterface,
} from "../ICronusTimeOracle";

const _abi = [
  {
    inputs: [],
    name: "askOracle",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class ICronusTimeOracle__factory {
  static readonly abi = _abi;
  static createInterface(): ICronusTimeOracleInterface {
    return new utils.Interface(_abi) as ICronusTimeOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ICronusTimeOracle {
    return new Contract(address, _abi, signerOrProvider) as ICronusTimeOracle;
  }
}
