/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IMetaCompanyInfo,
  IMetaCompanyInfoInterface,
} from "../IMetaCompanyInfo";

const _abi = [
  {
    inputs: [],
    name: "createFranchise",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
];

export class IMetaCompanyInfo__factory {
  static readonly abi = _abi;
  static createInterface(): IMetaCompanyInfoInterface {
    return new utils.Interface(_abi) as IMetaCompanyInfoInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMetaCompanyInfo {
    return new Contract(address, _abi, signerOrProvider) as IMetaCompanyInfo;
  }
}
