/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IMetaBaseManager__factory } from "./IMetaBaseManager__factory";
export { IMetaCompanyInfo__factory } from "./IMetaCompanyInfo__factory";
export { IMetaCompanyManager__factory } from "./IMetaCompanyManager__factory";
export { IMetaFranchiseManager__factory } from "./IMetaFranchiseManager__factory";
export { IMetaFranchiseShareManager__factory } from "./IMetaFranchiseShareManager__factory";
