/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMidaDataFeedsConsumerSol from "./IMidaDataFeedsConsumer.sol";
export type { iMidaDataFeedsConsumerSol };
import type * as iMidasMultiNetworkRouterManagerSol from "./IMidasMultiNetworkRouterManager.sol";
export type { iMidasMultiNetworkRouterManagerSol };
export type { IMidasManager } from "./IMidasManager";
export type { IMidasMultiNetworkRouter } from "./IMidasMultiNetworkRouter";
