/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as iHermesMerkleAirdropSol from "./IHermesMerkleAirdrop.sol";
export { ITykheFortuneDistributor__factory } from "./ITykheFortuneDistributor__factory";
