/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iHermesMerkleAirdropSol from "./IHermesMerkleAirdrop.sol";
export type { iHermesMerkleAirdropSol };
export type { ITykheFortuneDistributor } from "./ITykheFortuneDistributor";
