/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { MetaERC1155ReceiverHolder } from "./MetaERC1155ReceiverHolder";
export type { MetaERC1155Upgradable } from "./MetaERC1155Upgradable";
