/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as iMetaErc1155ReceiverHolderCopySol from "./IMetaERC1155ReceiverHolder copy.sol";
export type { iMetaErc1155ReceiverHolderCopySol };
export type { IMetaERC1155Upgradable } from "./IMetaERC1155Upgradable";
