/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IMidasGoldRouter,
  IMidasGoldRouterInterface,
} from "../../../../contracts/midas/interfaces/IMidasGoldRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "string",
        name: "network",
        type: "string",
      },
    ],
    name: "getMinimunTokenAmout",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getNativeNetworkCurrencyPriceInUsd",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "string",
        name: "network",
        type: "string",
      },
    ],
    name: "getRequiredEthAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
    ],
    name: "isPayingWithNativeCurrency",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_amount",
        type: "uint256",
      },
    ],
    name: "swapBnbForUSD",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "tokenAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "swapTokensForStableCoin",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IMidasGoldRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IMidasGoldRouterInterface {
    return new utils.Interface(_abi) as IMidasGoldRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IMidasGoldRouter {
    return new Contract(address, _abi, signerOrProvider) as IMidasGoldRouter;
  }
}
