/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAletheiaTruthOracle,
  IAletheiaTruthOracleInterface,
} from "../../../../contracts/chainlinkOracles/interfaces/IAletheiaTruthOracle";

const _abi = [
  {
    inputs: [],
    name: "pickRandomFlowerColor",
    outputs: [
      {
        internalType: "string",
        name: "",
        type: "string",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IAletheiaTruthOracle__factory {
  static readonly abi = _abi;
  static createInterface(): IAletheiaTruthOracleInterface {
    return new utils.Interface(_abi) as IAletheiaTruthOracleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAletheiaTruthOracle {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAletheiaTruthOracle;
  }
}
